// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TornaguiaAsistente.Infrastructure.Persistence;

#nullable disable

namespace TornaguiaAsistente.Infrastructure.Migrations
{
    [DbContext(typeof(TornaguiaDbContext))]
    [Migration("20260826213316_AgregarCapacidadProductoQuitarCapacidadSolicitudProducto")]
    partial class AgregarCapacidadProductoQuitarCapacidadSolicitudProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<MultiPolygon>("Limites")
                        .HasColumnType("geometry");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.EntradaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EntradasInventario");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.ExcepcionTransitoLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ExcepcionesTransitoLocal");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.InventarioProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId", "ProductoId")
                        .IsUnique();

                    b.ToTable("InventarioProductos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.LoteProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LotesProductos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacidad")
                        .HasColumnType("numeric");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsNacional")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.RutaCalculada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartamentosIntermedios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DistanciaKm")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LineString>("Geometria")
                        .HasColumnType("geometry");

                    b.Property<int>("MunicipioDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioDestinoId");

                    b.HasIndex("MunicipioOrigenId");

                    b.ToTable("RutasCalculadas");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("DepartamentosIntermedios")
                        .HasColumnType("text[]");

                    b.Property<double?>("DistanciaKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("EsParaExportacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaDeclarado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("MunicipioDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipioOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroDeclaracionOrigen")
                        .HasColumnType("text");

                    b.Property<int?>("PaisDestinoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TiempoEstimadoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTornaguiaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.HasIndex("MunicipioDestinoId");

                    b.HasIndex("MunicipioOrigenId");

                    b.HasIndex("PaisDestinoId");

                    b.HasIndex("TipoTornaguiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.SolicitudDetalleTornaguia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinatarioIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PdfBytes")
                        .HasColumnType("bytea");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemitenteIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemitenteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<string>("TransportadorIdentificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportadorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.ToTable("SolicitudesDetalleTornaguia");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.SolicitudProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudesProductos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.TipoTornaguia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposTornaguia");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreguntaSeguridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSeguridadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.EntradaInventario", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.ExcepcionTransitoLocal", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Producto", "Producto")
                        .WithMany("ExcepcionesTransitoLocal")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Departamento");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.InventarioProducto", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Lote", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.LoteProducto", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Lote", "Lote")
                        .WithMany("LoteProductos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.RutaCalculada", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Municipio", "MunicipioDestino")
                        .WithMany()
                        .HasForeignKey("MunicipioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Municipio", "MunicipioOrigen")
                        .WithMany()
                        .HasForeignKey("MunicipioOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MunicipioDestino");

                    b.Navigation("MunicipioOrigen");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Lote", "Lote")
                        .WithOne("Solicitud")
                        .HasForeignKey("TornaguiaAsistente.Domain.Entities.Solicitud", "LoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Municipio", "MunicipioDestino")
                        .WithMany()
                        .HasForeignKey("MunicipioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Municipio", "MunicipioOrigen")
                        .WithMany()
                        .HasForeignKey("MunicipioOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Pais", "PaisDestino")
                        .WithMany()
                        .HasForeignKey("PaisDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TornaguiaAsistente.Domain.Entities.TipoTornaguia", "TipoTornaguia")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoTornaguiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("MunicipioDestino");

                    b.Navigation("MunicipioOrigen");

                    b.Navigation("PaisDestino");

                    b.Navigation("TipoTornaguia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.SolicitudDetalleTornaguia", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("DetalleTornaguia")
                        .HasForeignKey("TornaguiaAsistente.Domain.Entities.SolicitudDetalleTornaguia", "SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.SolicitudProducto", b =>
                {
                    b.HasOne("TornaguiaAsistente.Domain.Entities.Producto", "Producto")
                        .WithMany("SolicitudProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TornaguiaAsistente.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("SolicitudProductos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Lote", b =>
                {
                    b.Navigation("LoteProductos");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Producto", b =>
                {
                    b.Navigation("ExcepcionesTransitoLocal");

                    b.Navigation("SolicitudProductos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("DetalleTornaguia");

                    b.Navigation("SolicitudProductos");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.TipoTornaguia", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("TornaguiaAsistente.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
